FROM python:3.11-bullseye

# ✅ تثبيت FFmpeg وCMake
RUN apt-get update && apt-get install -y \
    ffmpeg \
    cmake \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install py-tgcalls==2.0.6 pyrofork yt-dlp fastapi uvicorn

COPY . .

CMD ["python", "-m", "music_bot.main"]
